//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcjtableapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string studid { get; set; }
        public string studname { get; set; }
        public string studaddr { get; set; }
        public string studgender { get; set; }
        public string studcity { get; set; }
    }
}
