//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcdbfirstapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mvcbatch27Entities : DbContext
    {
        public mvcbatch27Entities()
            : base("name=mvcbatch27Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<product> products { get; set; }
    
        public virtual int addproduct(string prodid, string prodname, Nullable<int> prodprice, string cateid)
        {
            var prodidParameter = prodid != null ?
                new ObjectParameter("prodid", prodid) :
                new ObjectParameter("prodid", typeof(string));
    
            var prodnameParameter = prodname != null ?
                new ObjectParameter("prodname", prodname) :
                new ObjectParameter("prodname", typeof(string));
    
            var prodpriceParameter = prodprice.HasValue ?
                new ObjectParameter("prodprice", prodprice) :
                new ObjectParameter("prodprice", typeof(int));
    
            var cateidParameter = cateid != null ?
                new ObjectParameter("cateid", cateid) :
                new ObjectParameter("cateid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addproduct", prodidParameter, prodnameParameter, prodpriceParameter, cateidParameter);
        }
    }
}
